apiVersion: v1
kind: Service
metadata:
  name: orders-app-metrics
  namespace: orders-system
  labels:
    app.kubernetes.io/name: orders-app-metrics
spec:
  selector:
    app: orders-app
  ports:
  - name: metrics
    port: 8000
    targetPort: 8000
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: orders-app-monitor
  namespace: orders-system
  labels:
    release: prometheus-stack
spec:
  selector:
    matchLabels:
      app.kubernetes.io/name: orders-app-metrics
  endpoints:
  - port: metrics
    interval: 5s
    path: /metrics
